### ISSUE TITLE
Recursive clone fails on v0.8.1 and v0.8.0

### ISSUE THREAD

**Issue by oliverdain** [facebookarchive/caffe2#1231] opened 2017-09-18 18:32 UTC
```
$ git clone --recursive -b v0.8.1 --depth=1 --single-branch https://github.com/caffe2/caffe2.git

...

Submodule path 'third_party/cnmem': checked out '28a182d49529da49f4ac4e3941cec3edf16b3540'
error: no such remote ref b1370adb972a8345de92e2d69e61daf7f9bce43e
Fetched in submodule path 'third_party/cub', but it did not contain b1370adb972a8345de92e2d69e61daf7f9bce43e. Direct fetching of that commit failed.
```

I'm guessing that they deleted some commits or something. Given that 0.8.1 is the most recent release it might make sense to update the submodule to use a hash that exists and is compatible.

**Comment by oliverdain** [comment] 2017-09-18 18:48
Fails on 0.8.0 too though it's a different commit that's referenced: 89de7ab20167909bc2c4f8acd397671c47cf3c0d

Suggestion: using git subtree instead of submodule would eliminate these (and other) issues.

**Comment by lukeyeager** [comment] 2017-09-18 21:01
Duplicate of https://github.com/caffe2/caffe2/issues/1081, https://github.com/caffe2/caffe2/issues/1107, https://github.com/caffe2/caffe2/issues/1148.

**Comment by Yangqing** [comment] 2017-09-23 05:27
This is because cub did a hard push at some point. Try deleting the cub submodule and redo git submodule update --init.

To delete the cub submodule, follow instructions here: https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule

**Comment by orionr** [comment] 2018-01-31 16:50
We've updated Docker to use master instead of the v0.8.1 release branch with https://github.com/caffe2/caffe2/pull/1520, which removes any references to release branches in the code. Let us know if we missed one!

For now, though, I'd recommend that everyone be on master. Too bad about the hard push on cub's part - that makes git submodules difficult. :-/

**Closed as completed by orionr** 2018-01-31 16:50 UTC
Labels: Answered, Downstream problem

**Comment by agilmor** [comment] 2018-03-03 17:26
Besides the commit-hash, is there any way to know if v0.8.x was pointing to any specific tag of cub?
If we have this information, at least we could still manually checkout the right version of cub, right?
Or was caffe2 poiting to a non-tagged commit of cub?

Thanks!
