### ISSUE TITLE
db_. Cannot open db:

### ISSUE THREAD

**Issue by miaoshuyu** [facebookarchive/caffe2#2328] opened 2018-03-20 12:36 UTC
I am learning the Tutorials -- MNIST - Create a CNN from Scratch as https://caffe2.ai/docs/tutorial-MNIST.html#main_wrap
when I run the code as follow:
![image](https://user-images.githubusercontent.com/26992220/37654599-b1fd072e-2c7d-11e8-8378-7b64a5f6f530.png)
there is an error .
![image](https://user-images.githubusercontent.com/26992220/37654616-c28b2c56-2c7d-11e8-813a-958aa55d5687.png)
and my file path is right:
![image](https://user-images.githubusercontent.com/26992220/37654735-239dea38-2c7e-11e8-95bb-5ec8a87c9997.png)
Who knows how to solve this problem?Thanks a lot .
My platform:caffe2+anaconda3+cmake3+vs2017

**Comment by pjh5** [comment] 2018-03-21 18:01
This is a duplicate of #2282 

I will close this issue. Please follow #2282

**Closed as completed by pjh5** 2018-03-21 18:01 UTC
