### ISSUE TITLE
ubuntu14.04: recipe for target ''[78%]:elementwise_op_gpu_test.cc:(.text+0x89): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'''

### ISSUE THREAD

**Issue by pingjun18-li** [facebookarchive/caffe2#2096] opened 2018-03-01 07:30 UTC
### System information

 CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   System                : unbuntu14.04
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf include path : /usr/include
--   Protobuf libraries    : optimized;/usr/lib/x86_64-linux-gnu/libprotobuf.so;debug;/usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread
--   BLAS                  : Eigen
--   CXX flags             :  -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   :
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.13
--     Python library      : /data/xiaobing.wang/anaconda2/lib/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 5.1.10
--     CUDA root directory : /usr/local/cuda-8.0
--     CUDA library        : /usr/local/cuda-8.0/lib64/stubs/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda-8.0/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda-8.0/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda-8.0/include
--     NVCC executable     : /usr/local/cuda-8.0/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc

--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.21

### CMake summary output
[ 78%] Linking CXX executable ../bin/elementwise_op_gpu_test
/usr/bin/cmake: /data/xiaobing.wang/anaconda2/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /data/xiaobing.wang/anaconda2/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /data/xiaobing.wang/anaconda2/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
/usr/bin/cmake: /data/xiaobing.wang/anaconda2/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
CMakeFiles/elementwise_op_gpu_test.dir/operators/elementwise_op_gpu_test.cc.o: In function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .isra.150]':
elementwise_op_gpu_test.cc:(.text+0x89): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
CMakeFiles/elementwise_op_gpu_test.dir/operators/elementwise_op_gpu_test.cc.o: In function `void caffe2::TypeMeta::_CopyNotAllowed<caffe2::Tensor<caffe2::CUDAContext> >(void const*, void*, unsigned long)':
elementwise_op_gpu_test.cc:(.text._ZN6caffe28TypeMeta15_CopyNotAllowedINS_6TensorINS_11CUDAContextEEEEEvPKvPvm[_ZN6caffe28TypeMeta15_CopyNotAllowedINS_6TensorINS_11CUDAContextEEEEEvPKvPvm]+0x92): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/elementwise_op_gpu_test.dir/operators/elementwise_op_gpu_test.cc.o: In function `caffe2::OperatorBase::AddRelatedBlobInfo(caffe2::EnforceNotMet*)':
elementwise_op_gpu_test.cc:(.text._ZN6caffe212OperatorBase18AddRelatedBlobInfoEPNS_13EnforceNotMetE[_ZN6caffe212OperatorBase18AddRelatedBlobInfoEPNS_13EnforceNotMetE]+0xda): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)'
elementwise_op_gpu_test.cc:(.text._ZN6caffe212OperatorBase18AddRelatedBlobInfoEPNS_13EnforceNotMetE[_ZN6caffe212OperatorBase18AddRelatedBlobInfoEPNS_13EnforceNotMetE]+0x107): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
elementwise_op_gpu_test.cc:(.text._ZN6caffe212OperatorBase18AddRelatedBlobInfoEPNS_13EnforceNotMetE[_ZN6caffe212OperatorBase18AddRelatedBlobInfoEPNS_13EnforceNotMetE]+0x117): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
elementwise_op_gpu_test.cc:(.text._ZN6caffe212OperatorBase18AddRelatedBlobInfoEPNS_13EnforceNotMetE[_ZN6caffe212OperatorBase18AddRelatedBlobInfoEPNS_13EnforceNotMetE]+0x217): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)'
elementwise_op_gpu_test.cc:(.text._ZN6caffe212OperatorBase18AddRelatedBlobInfoEPNS_13EnforceNotMetE[_ZN6caffe212OperatorBase18AddRelatedBlobInfoEPNS_13EnforceNotMetE]+0x244): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
elementwise_op_gpu_test.cc:21'
../lib/libcaffe2_gpu.so: undefined reference to `std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)())@GLIBCXX_3.4.21'
../lib/libcaffe2.so: undefined reference to `std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)())'
../lib/libcaffe2_gpu.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*)@GLIBCXX_3.4.21'
../lib/libcaffe2.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)'
../lib/libcaffe2_gpu.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::end()@GLIBCXX_3.4.21'
../lib/libcaffe2_gpu.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libglog.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/usr/lib/x86_64-linux-gnu/libprotobuf.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
....
...
....
...
...
...
../lib/libcaffe2_gpu.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const@GLIBCXX_3.4.21'
../lib/libcaffe2_gpu.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
../lib/libcaffe2.so: undefined reference to `__cxa_throw_bad_array_new_length'
../lib/libcaffe2_gpu.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
../lib/libcaffe2_gpu.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_set_length(unsigned long)@GLIBCXX_3.4.21'
../lib/libcaffe2_gpu.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/elementwise_op_gpu_test.dir/build.make:124: recipe for target 'bin/elementwise_op_gpu_test' failed
make[3]: *** [bin/elementwise_op_gpu_test] Error 1
make[3]: Leaving directory '/data/xiaobing.wang/pingjun.li/caffe2-new/build'
CMakeFiles/Makefile2:1207: recipe for target 'caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all' failed
make[2]: *** [caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all] Error 2
make[2]: Leaving directory '/data/xiaobing.wang/pingjun.li/caffe2-new/build'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/data/xiaobing.wang/pingjun.li/caffe2-new/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

******** Summary ********
I don't know

**Comment by pjh5** [comment] 2018-03-02 16:00
This is a duplicate of #1980 . Please read that discussion

**Closed as completed by pjh5** 2018-03-02 16:00 UTC

**Comment by leokwu** [comment] 2018-11-22 03:42
I have the same problem. Is there a solution?

**Comment by orionr** [comment] 2018-11-26 15:36
@411506656 please look at https://github.com/caffe2/caffe2/issues/1980. You likely need to create a separate conda environment and make sure that all installed content has the right ABI.
