### ISSUE TITLE
CUDNN_DATA_INT32 in Ubuntu16.04

### ISSUE THREAD

**Issue by jimmyoic** [facebookarchive/caffe2#1674] opened 2017-12-29 09:27 UTC
* Operating system: Ubuntu16.04
* Compiler version: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
* CMake version: 3.5.1

Cuda 8.0 / cudnn 6

I got the same problem similar with #1343 , which caused by the compatibility of cudnn 5.1.
I had re-installed all the libraries (CUDA 8.0, cudnn6 ... ) and then rebuilt caffe2 but still failed.

![image](https://user-images.githubusercontent.com/7804036/34433902-5e6162ea-ecbd-11e7-81af-64ade066c45a.png)

Did anyone have the same problems?
Thanks!

**Comment by pietern** [comment] 2017-12-29 23:40
Did you reuse your original build directory?

It can help to remove it entirely, recreate the build directory, and re-run CMake from scratch.

**Comment by jimmyoic** [comment] 2017-12-30 06:00
No.
I deleted all the original files and got the up-to-date version of caffe2. However, I still got this problem. 

BTW, I also tried on Windows 10 without having this problem, but I got lnk error that it couldn't find the reference of CUDA libraries.

**Comment by Yangqing** [comment] 2018-01-02 23:59
If the issue is caused by cudnn 5.1 - it should be fixed by https://github.com/caffe2/caffe2/commit/55f6fea3a93a4e9e1d1256e1ec51afa1d4ce6f70 .

Is it possible that you have dangling cudnn 5.1 header file somewhere?

**Comment by jimmyoic** [comment] 2018-01-03 01:06
I think it is possible that cudnn 5.1 header exists somewhere since the server is shared by a group. I'll check it thoroughly. Thanks for the response!

**Closed as completed** 2018-01-05 19:42 UTC
Labels: build
