### ISSUE TITLE
caffe2 will set link time dependency on libcudnn.so.5 even when this library doesn't exist at configure time

### ISSUE THREAD

**Issue by ezyang** [facebookarchive/caffe2#959] opened 2017-07-24 20:17 UTC
Steps to reproduce:
1. Get a machine that doesn't have CuDNN installed
2. Install CuDNN to a non-standard location
3. From your standard location, create a `libcudnn.so` and `libcudnn.a` symlink to the shared library in the non-standard location. DO NOT create a `libcudnn.so.5` (or whatever the version is) symlink.
4. Configure and build caffe2
5. Link a program against caffe2

Expected result: Either everything succeeds, or when I configure in step (4), caffe2 tells me my CuDNN install is broken.

Actual result: CuDNN detects `libcudnn.so` and concludes that CuDNN is installed, but then proceeds to record a dynamic dependency against `libcudnn.so.5` (which doesn't exist), causing subsequent linking to fail.

CC @justinchiu

**Comment by deepali-c** [comment] 2017-07-25 13:43
Seems related to #887.

**Comment by pietern** [comment] 2017-12-12 06:00
I think this is caused by the SONAME property of the library itself, regardless of symlinks.

I've not seen this pop up again in the meantime, so closing this issue.

**Closed as completed by pietern** 2017-12-12 06:00 UTC
Labels: build
