### ISSUE TITLE
[super_resolution]speed_benchmark : not executable: 64-bit ELF file

### ISSUE THREAD

**Issue by Nanda0001** [facebookarchive/caffe2#1805] opened 2018-01-25 00:46 UTC
### System information

* Operating system:  LINUX UBUNTU 16.04 64bit

```
******** Summary ********
super_resolution_with_caffe2.py or PytorchCaffe2SuperResolution
**

> $ adb shell /data/local/tmp/speed_benchmark

**
I ran the above file. but it came out some error like this
**/system/bin/sh: /data/local/tmp/speed_benchmark: not executable: 64-bit ELF file**

I changed permission in ADB
**root@generic_x86:/data/local/tmp # chmod 755 speed_benchmark**
**root@generic_x86:/data/local/tmp # chmod 777 speed_benchmark**
```

Please Give me some advice. Thank you

**Comment by Maratyszcza** [comment] 2018-01-25 01:04
What are you trying to do? You seemingly built Caffe2 for your host system, and are trying to run the binary built for your host systems on your Android phone.

**Comment by Maratyszcza** [comment] 2018-01-27 04:39
Duplicate of #1818

**Closed as completed by Maratyszcza** 2018-01-27 04:39 UTC
Labels: duplicate
