### ISSUE TITLE
Cub submodule for the latest release (v0.8.0)

### ISSUE THREAD

**Issue by paul-mesnilgrente** [facebookarchive/caffe2#1148] opened 2017-08-30 09:46 UTC
Hello everyone,

I tried to compile for the 0.8.0 version with this commands:

```bash
git clone --recursive git@github.com:/caffe2/caffe2 && cd caffe2
git co v0.8.0
git submodule update
```

The problem is that when I execute the last command, the `third_party/cub` commit is not found, this is the output:

```text
fatal: reference is not a tree: 89de7ab20167909bc2c4f8acd397671c47cf3c0d
Unable to checkout '89de7ab20167909bc2c4f8acd397671c47cf3c0d' in submodule path 'third_party/cub'
```

And effectively the commit is not found, I checked with this (inside `third_party/cub`): `git branch -r --contains 89de7ab20167909bc2c4f8acd397671c47cf3c0d`.

I tried to compile hoping that the differences wouldn't be a problem but it is, the architecture in this submodule has changed and it doesn't compile.

Is there a way to fix this? Maybe you can give the version of CUB that is used in the submodule and I will can check out on this version.

**Comment by lukeyeager** [comment] 2017-08-30 16:14
Duplicate of https://github.com/caffe2/caffe2/issues/1081, https://github.com/caffe2/caffe2/issues/1107.

**Comment by Yangqing** [comment] 2017-09-23 05:26
This is because cub did a hard push at some point. Try deleting the cub submodule and redo git submodule update --init.

To delete the cub submodule, follow instructions here: https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule

**Closed as completed by Yangqing** 2017-09-23 05:26 UTC
Labels: Answered, Downstream problem
