### ISSUE TITLE
undefined reference to symbol '_ZN3MPI8Datatype4FreeEv' compiled on ubuntu1604

### ISSUE THREAD

**Issue by dinglong1020** [facebookarchive/caffe2#2300] opened 2018-03-18 08:29 UTC
make[3]: Entering directory '/home/ubuntu/caffe2-master/build'
make[3]: Leaving directory '/home/ubuntu/caffe2-master/build'
make[3]: Entering directory '/home/ubuntu/caffe2-master/build'
[ 92%] Linking CXX executable ../bin/mpi_test
/usr/bin/ld: CMakeFiles/mpi_test.dir/mpi/mpi_test.cc.o: undefined reference to symbol '_ZN3MPI8Datatype4FreeEv'
//usr/lib/libmpi_cxx.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/mpi_test.dir/build.make:100: recipe for target 'bin/mpi_test' failed
make[3]: *** [bin/mpi_test] Error 1
make[3]: Leaving directory '/home/ubuntu/caffe2-master/build'
CMakeFiles/Makefile2:2654: recipe for target 'caffe2/CMakeFiles/mpi_test.dir/all' failed
make[2]: *** [caffe2/CMakeFiles/mpi_test.dir/all] Error 2
make[2]: Leaving directory '/home/ubuntu/caffe2-master/build'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/caffe2-master/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jabaa** [comment] 2018-03-18 23:56
Duplicate of https://github.com/caffe2/caffe2/issues/2144

**Comment by pjh5** [comment] 2018-03-19 18:46
@dinglong1020 do you want to build with MPI? MPI is used for distributed training. If yes, can you give me the output of `mpirun --version` , the output of the `cmake` command, and how you tried to install Cafffe2?

If you do not care about MPI then I will close this as a duplicate.

**Comment by pjh5** [comment] 2018-03-28 16:52
Closing as duplicate

**Closed as completed by pjh5** 2018-03-28 16:52 UTC
Labels: build, CUDA
