### ISSUE TITLE
Compile error with cpu-only build - gcc7

### ISSUE THREAD

**Issue by dbermond** [facebookarchive/caffe2#805] opened 2017-06-15 02:38 UTC
I'm getting this compile error when trying to build caffe2 without gpu support (cpu-only build):
```
[ 64%] Building CXX object caffe2/CMakeFiles/Caffe2_CPU.dir/operators/remove_data_blocks_op.cc.o
In file included from /home/user/abs/caffe2-cpu-git/src/caffe2-cpu-git/caffe2/operators/recurrent_network_op.cc:1:0:
/home/user/abs/caffe2-cpu-git/src/caffe2-cpu-git/caffe2/operators/recurrent_network_op.h: In member function ‘bool caffe2::AccumulateInputGradientOp<T, Context>::RunOnDevice()’:
/home/user/abs/caffe2-cpu-git/src/caffe2-cpu-git/caffe2/operators/recurrent_network_op.h:761:50: error: cannot call member function ‘const T& caffe2::OperatorBase::Input(int) [with T = caffe2::Tensor<caffe2::CPUContext>]’ without object
         OperatorBase::Input<Tensor<CPUContext>>(0).template data<int32_t>()[0];
                                                  ^
make[2]: *** [caffe2/CMakeFiles/Caffe2_CPU.dir/build.make:2895: caffe2/CMakeFiles/Caffe2_CPU.dir/operators/recurrent_network_op.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:427: caffe2/CMakeFiles/Caffe2_CPU.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

System Information:
**OS:** Arch Linux x86_64
**Compiler:** gcc 7.1.1
**Caffe2:** git master (currently at 0.7.0.r434.g4c76b747)

It builds fine when enabling gpu support and using gcc 5.4.0 (due to cuda).

Steps to reproduce and complete output are attached.

[caffe2-steps-and-output.txt](https://github.com/caffe2/caffe2/files/1076418/caffe2-steps-and-output.txt)

**Comment by cuepi** [comment] 2017-06-30 15:43
This is happening to me in a Mac too. 

System Information:
**OS:** Mac OSX
**Compiler:** gcc-7 (Homebrew GCC 7.1.0 --without-multilib) 7.1.0
**Caffe2:** git master (a57251bb0ad5339cb54cecd66ed615535f7e334b)

[Caffe2-805-Sample2.txt](https://github.com/caffe2/caffe2/files/1115769/Caffe2-805-Sample2.txt)

**Comment by dbermond** [comment] 2017-06-30 16:41
> This is happening to me in a Mac too.

Good to know that I'm not alone :)

**Comment by decm32** [comment] 2017-07-05 10:19
same problem,centos6,gcc7.1

**Comment by changyp6** [comment] 2017-08-04 09:50
Same error Fedora 26 gcc7.1.1

**Comment by graykevinb** [comment] 2017-08-12 23:46
Same exact error, on Fedora 26. tried with 4 threads and 1, same results.

**Comment by janboeye** [comment] 2017-09-07 08:52
same error on ubuntu 17.10

**Comment by BrettRyland** [comment] 2017-09-14 13:01
I get the same error for a git-master GPU build using gcc-7.2.0-4 (Debian unstable) with gcc-5.4.1-12 for the NVCC compiler and using cmake.
Here's my [CMakeCache.txt](https://github.com/caffe2/caffe2/files/1302999/CMakeCache.txt) and [make output](https://github.com/caffe2/caffe2/files/1303000/output.txt) in case they're useful.

**Comment by cbalint13** [comment] 2017-09-14 14:46
Can try a quick patch.

```
--- caffe2/queue/queue_ops.h.orig	2017-07-25 12:31:27.095636895 +0300
+++ caffe2/queue/queue_ops.h	2017-07-25 12:32:17.606468973 +0300
@@ -18,12 +18,11 @@
 
   bool RunOnDevice() override {
     const auto capacity =
-        OperatorBase::template GetSingleArgument<int>("capacity", 1);
+        GetSingleArgument("capacity", 1);
     const auto numBlobs =
-        OperatorBase::template GetSingleArgument<int>("num_blobs", 1);
+        GetSingleArgument("num_blobs", 1);
     const auto enforceUniqueName =
-        OperatorBase::template GetSingleArgument<int>(
-            "enforce_unique_name", false);
+        GetSingleArgument("enforce_unique_name", false);
     const auto fieldNames =
         OperatorBase::template GetRepeatedArgument<std::string>("field_names");
     CAFFE_ENFORCE_EQ(this->OutputSize(), 1);
```

**Comment by BrettRyland** [comment] 2017-09-15 09:18
This [diff](https://github.com/caffe2/caffe2/files/1305798/caffe2.diff.txt) allows me to successfully build now.

Edit: I'm not sure why separating `OperatorBase::Input<Tensor<CPUContext>>(0).template data<int32_t>()[0];` into two commands allows it to compile... it's quite possible that it's not doing what it's supposed to be doing.

Note: in order to successfully run the command
`optirun python -m caffe2.python.operator_test.relu_op_test`
I had to set `PYTHONPATH=/usr/local` and `LD_LIBRARY_PATH=/usr/local/lib:/usr/local/nccl/lib` as I'd installed nccl2 (from NVIDIA) in `/usr/local/nccl`. Also, I have an optimus system, hence the `optirun` command before `python`, without which caffe2 doesn't think I have a GPU.

**Comment by stefan-it** [comment] 2017-09-19 09:31
On Arch Linux with GCC 7.2 I got the same error message. But with the patch proposed by  @BrettRyland the compilation was successful!

**Comment by Yangqing** [comment] 2017-09-24 02:38
That is interesting analysis - seems to be something compiler related, since all other compilers run correctly... @akyrola do you mind taking a look, or basically including @BrettRyland 's diff?

**Comment by gemarcano** [comment] 2017-11-15 20:39
I'm not sure, but at a glance it looks like clang accepts this code, so maybe this is a GCC regression?

**Comment by pietern** [comment] 2017-12-11 17:24
Reproduced the issue. It only happens on GCC 7. Looking into it.

**Comment by pietern** [comment] 2017-12-11 21:36
This is merged.

**Comment by pietern** [comment] 2017-12-11 21:37
Thanks @BrettRyland for posting the initial fix!

**Closed as completed by pietern** 2017-12-11 21:36 UTC
Labels: build
