### ISSUE TITLE
../lib/libcaffe2.so: undefined reference to `google::protobuf::internal::AssignDescriptors(std::__cxx11::basic_string

### ISSUE THREAD

**Issue by yutingchen1211** [facebookarchive/caffe2#1912] opened 2018-02-08 00:48 UTC
Was trying to do custom anaconda install but consistently fails due to protobuf related error. Tried re-creating virtual environment, uninstalling protobuf package but still fails. 

So I went to use the conda build version, but it failed too. Please see below, thanks!

### System information

* Operating system: Ubuntu 16.04
* Compiler version: 
* CMake version: 3.4.1
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA): CUDA

### CMake summary output

```
******** Summary ********
conda build conda/cuda
/home/yuting/anaconda3/envs/caffe2_py27/lib/python2.7/site-packages/conda_build/environ.py:328: UserWarning: The environment variable 'CONDA_CMAKE_ARGS' is undefined.
  UserWarning
BUILD START: caffe2-cuda-0.8.dev-py27_0
    (actual version deferred until further download or env creation)
updating index in: /home/yuting/anaconda3/envs/caffe2_py27/conda-bld/linux-64
updating index in: /home/yuting/anaconda3/envs/caffe2_py27/conda-bld/noarch

The following NEW packages will be INSTALLED:

    blas:             1.1-openblas                  conda-forge
    bzip2:            1.0.6-1                       conda-forge
    ca-certificates:  2017.11.5-0                   conda-forge
    cairo:            1.14.6-5                      conda-forge
    certifi:          2017.11.5-py27_0              conda-forge
    cmake:            3.10.0-4                      conda-forge
    curl:             7.55.1-0                      conda-forge
    dbus:             1.10.22-0                     conda-forge
    expat:            2.2.5-0                       conda-forge
    ffmpeg:           3.2.4-3                       conda-forge
    fontconfig:       2.12.1-6                      conda-forge
    freetype:         2.7-2                         conda-forge
    future:           0.16.0-py27_0                 conda-forge
    gettext:          0.19.7-1                      conda-forge
    gflags:           2.2.1-0                       conda-forge
    giflib:           5.1.4-0                       conda-forge
    glib:             2.51.4-0                      conda-forge
    glog:             0.3.5-0                       conda-forge
    gst-plugins-base: 1.8.0-0                       conda-forge
    gstreamer:        1.8.0-2                       conda-forge
    harfbuzz:         1.3.4-2                       conda-forge
    hdf5:             1.10.1-1                      conda-forge
    icu:              58.2-0                        conda-forge
    jasper:           1.900.1-4                     conda-forge
    jpeg:             9b-2                          conda-forge
    krb5:             1.14.2-0                      conda-forge
    libffi:           3.2.1-3                       conda-forge
    libgfortran:      3.0.0-1                                  
    libiconv:         1.15-0                        conda-forge
    libpng:           1.6.28-2                      conda-forge
    libssh2:          1.8.0-2                       conda-forge
    libtiff:          4.0.7-1                       conda-forge
    libuv:            1.11.0-0                      conda-forge
    libwebp:          0.5.2-7                       conda-forge
    libxcb:           1.12-1                        conda-forge
    libxml2:          2.9.7-0                       conda-forge
    lmdb:             0.9.21-0                      conda-forge
    ncurses:          5.9-10                        conda-forge
    numpy:            1.14.0-py27_blas_openblas_200 conda-forge [blas_openblas]
    openblas:         0.2.20-7                      conda-forge
    opencv:           3.3.0-py27_blas_openblas_203  conda-forge [blas_openblas]
    openssl:          1.0.2n-0                      conda-forge
    pcre:             8.39-0                        conda-forge
    pip:              9.0.1-py27_1                  conda-forge
    pixman:           0.34.0-1                      conda-forge
    protobuf:         3.5.1-py27_3                  conda-forge
    python:           2.7.14-4                      conda-forge
    qt:               5.6.2-3                       conda-forge
    readline:         7.0-0                         conda-forge
    rhash:            1.3.4-0                       conda-forge
    scipy:            1.0.0-py27_blas_openblas_201  conda-forge [blas_openblas]
    setuptools:       38.4.0-py27_0                 conda-forge
    six:              1.11.0-py27_1                 conda-forge
    sqlite:           3.20.1-2                      conda-forge
    tk:               8.6.7-0                       conda-forge
    wheel:            0.30.0-py27_2                 conda-forge
    x264:             20131217-3                    conda-forge
    xorg-libxau:      1.0.8-3                       conda-forge
    xorg-libxdmcp:    1.1.2-3                       conda-forge
    xz:               5.2.3-0                       conda-forge
    zlib:             1.2.11-0                      conda-forge


WARNING: conda-build appears to be out of date. You have version 2.1.18 but the
latest version is 3.4.0. Run

conda update -n root conda-build

to get the latest version.

Copying /home/yuting/caffe2 to /home/yuting/anaconda3/envs/caffe2_py27/conda-bld/caffe2-cuda_1518049542818/work
Error: Failed to render jinja template in /home/yuting/caffe2/conda/cuda/meta.yaml:
'protobuf' is undefined

(caffe2_py27) yuting@PPD-ubuntu:~/caffe2$ which protoc
/home/yuting/anaconda3/envs/caffe2_py27/bin/protoc

```

**Comment by pjh5** [comment] 2018-02-08 01:25
Can you try uploading your conda-build version? This environment looks to be working on our end

**Comment by yutingchen1211** [comment] 2018-02-08 02:12
Thanks for the reply.

My conda-build version is 2.1.18 and conda version is 4.3.33. It seems that both of these are not up-to-date. However when I try to do "conda update conda" and "conda update conda-build" it does not update them for me...  Any thoughts?

****************************************
```
yuting@PPD-ubuntu:~$ conda update conda-build
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/yuting/anaconda3:
#
conda-build               2.1.18                   py36_0    conda-forge
yuting@PPD-ubuntu:~$ conda update conda
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/yuting/anaconda3:
#
conda                     4.3.33                   py36_0    conda-forge
```

**Comment by pjh5** [comment] 2018-02-08 02:25
Are you running these in the correct conda environment?
You can try explicitly asking for the version like `conda install conda-build==3.4.0`

**Comment by yutingchen1211** [comment] 2018-02-08 02:45
I believe so... Btw do you know how to update conda and conda-build, when I first try to update conda, it actually downgraded from 4.6 to  4.33.

**Comment by pjh5** [comment] 2018-02-08 02:50
I don't think the conda version matters as much as the conda-build version. Try `conda install conda-build==3.4.0`

**Comment by yutingchen1211** [comment] 2018-02-08 03:03
@pjh5 Thanks Paul. I can indeed update the conda-build version. And conda-build is running now. However do you know how can I use conda build to build on python 2.7 instead of 3.6? I am running conda build in a python 2.7 conda env, however it seems conda build is building on 3.6 (my default anaconda python version).

**Comment by pjh5** [comment] 2018-02-08 17:32
This problem is now a duplicate of https://github.com/caffe2/caffe2/issues/1872

**Closed as completed** 2018-02-13 19:57 UTC
Labels: build, Protobuf

**Comment by pjh5** [comment] 2018-02-16 23:39
For future discussion, see #1980
