### ISSUE TITLE
How can I improve this error? : This file was generated by a new version of protocol 

### ISSUE THREAD

**Issue by HIKAGE56** [facebookarchive/caffe2#776] opened 2017-06-10 08:16 UTC
I tried to install caffe2 along tutorial, but I can’t compile it.

#error
[  1%] Built target gmock
[  3%] Built target gmock_main
[  4%] Built target gtest
[  4%] Built target gtest_main
[  4%] Building CXX object caffe/proto/CMakeFiles/Caffe_PROTO.dir/caffe.pb.cc.o
In file included from /Users/kamenoko/caffe2/build/caffe/proto/caffe.pb.cc:5:
/Users/kamenoko/caffe2/build/caffe/proto/caffe.pb.h:12:2: error: This file was
      generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
/Users/kamenoko/caffe2/build/caffe/proto/caffe.pb.h:13:2: error: incompatible
      with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
/Users/kamenoko/caffe2/build/caffe/proto/caffe.pb.h:14:2: error: your headers.
#error your headers.
 ^
/Users/kamenoko/caffe2/build/caffe/proto/caffe.pb.h:25:10: fatal error: 
      'google/protobuf/generated_message_table_driven.h' file not found
#include <google/protobuf/generated_message_table_driven.h>
         ^
4 errors generated.
make[2]: *** [caffe/proto/CMakeFiles/Caffe_PROTO.dir/caffe.pb.cc.o] Error 1
make[1]: *** [caffe/proto/CMakeFiles/Caffe_PROTO.dir/all] Error 2
make: *** [all] Error 2

I thought caffe2 needs 3.3.1 protoc , so installed it.
But, the error doesn’t change  though my protoc version was upgrade 3.3.0 from
3.2.0.
How can I improve this error?

[OS] MacOS X

**Comment by Seungsoo-Yang** [comment] 2017-06-12 09:42
libprotoc 2.5.0, my protoc works with caffe2

**Comment by HIKAGE56** [comment] 2017-06-12 12:59
Sorry, I can solved(?) this error.
I couldn't change protocol version,
version 3.2.0 successed.

But I have new error.

#error 
[  1%] Built target gmock
[  2%] Built target gmock_main
[  3%] Built target gtest
[  4%] Built target gtest_main
[  4%] Building CXX object caffe/proto/CMakeFiles/Caffe_PROTO.dir/caffe.pb.cc.o
In file included from /Users/kamenoko/caffe2/build/caffe/proto/caffe.pb.cc:5:
/Users/kamenoko/caffe2/build/caffe/proto/caffe.pb.h:22:10: fatal error: 
      'google/protobuf/arena.h' file not found
#include <google/protobuf/arena.h>
         ^
1 error generated.
make[2]: *** [caffe/proto/CMakeFiles/Caffe_PROTO.dir/caffe.pb.cc.o] Error 1
make[1]: *** [caffe/proto/CMakeFiles/Caffe_PROTO.dir/all] Error 2
make: *** [all] Error 2

This error maybe happen in other git module 'google/protobuf'.
But I can rewrite other module.
What I should do?

**Comment by pietern** [comment] 2017-10-11 19:26
This was caused by a mismatch between the version of protoc (the binary that generates source code from protobuf definitions) and libprotobuf (the protobuf runtime library). This is addressed in #1328 which will be merged shortly. Closing this issue.

**Closed as completed by pietern** 2017-10-11 19:26 UTC
