### ISSUE TITLE
Build issue in Ubuntu 16.04

### ISSUE THREAD

**Issue by charlesrwest** [facebookarchive/caffe2#389] opened 2017-04-24 02:48 UTC
I'm having some issue compiling in Ubuntu.  I get the error below with failure to find libnvidia-fatbinaryloader.so.375.51.  As far as I can tell, those files have been installed to 

/usr/lib32/nvidia-375/libnvidia-fatbinaryloader.so.375.51
/usr/lib/nvidia-375/libnvidia-fatbinaryloader.so.375.51

Does anyone know which cmake modules I should be modifying to allow it to locate that?

Thanks.

> 

[ 74%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/operators/top_k_gpu.cc.o
[ 74%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/queue/queue_ops_gpu.cc.o
[ 74%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/sgd/iter_op_gpu.cc.o
[ 75%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/sgd/learning_rate_op_gpu.cc.o
[ 75%] Linking CXX shared library libCaffe2_GPU.so
[ 75%] Built target Caffe2_GPU
Scanning dependencies of target print_core_object_sizes
[ 75%] Building CXX object caffe2/CMakeFiles/print_core_object_sizes.dir/binaries/print_core_object_sizes.cc.o                                                                    
[ 75%] Linking CXX executable binaries/print_core_object_sizes
[ 75%] Built target print_core_object_sizes
Scanning dependencies of target inspect_gpus
[ 75%] Building CXX object caffe2/CMakeFiles/inspect_gpus.dir/binaries/inspect_gpus.cc.o
[ 75%] Linking CXX executable binaries/inspect_gpus
/usr/bin/ld: warning: libnvidia-fatbinaryloader.so.375.51, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Get_FatBinary_From_Object'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_section_header'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `gpuInfoRunsOn'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf_end'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_shnum'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `fatBinaryCtl'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_symbol_shndx'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Free_Fatbinary'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_string_at_offset'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_symbol_shndx'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `fatBinaryCtl_Compile'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_file_header'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `fatBinaryCtl_PickCandidate'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_string_at_offset'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Start'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_typed_section_header'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Finish'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `gpucompSetLogLine'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Next_Library_Member'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_section_name'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf_is_64bit'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf_size'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `fatBinaryCtl_Delete'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_symbol_name'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_shnum'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Add_Cubin'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_section_contents'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_section_header'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `stdGetThreadContext'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_named_section_header'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Delete'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Finish_Reading_Library'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_typed_section_header'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `gpucompRestoreLogLine'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_file_header'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Load_Host_Object'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Start_Reading_Library'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elfLink_Free_Host_Object'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf64_named_section_header'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_symbol_name'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `elf32_section_name'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcuda.so: undefined reference to `fatBinaryCtl_Create'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/inspect_gpus.dir/build.make:135: recipe for target 'caffe2/binaries/inspect_gpus' failed
make[2]: *** [caffe2/binaries/inspect_gpus] Error 1
CMakeFiles/Makefile2:1529: recipe for target 'caffe2/CMakeFiles/inspect_gpus.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/inspect_gpus.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by aaronmarkham** [comment] 2017-04-25 16:15
Hi Charles, I haven't seen this particular problem pop up before, but I did get some pretty obscure error messages from the NVIDIA part of the compile when my video drivers were not up-to-date. Updating the drivers and then reinstalling CUDA and cuDNN did the trick.

**Comment by Yanxxx** [comment] 2017-04-27 16:57
That probably is caused by the UEFI BOIS secure mode. You need to turn off the secure boot mode in BOIS setting. Otherwise the Nvidia driver cannot be installed correctly. 
After disable the secure boot mode, just re-install the nvidia driver, then the problem can be solved.

**Comment by kyu-sz** [comment] 2017-05-01 06:39
Try adding "/usr/lib/nvidia-375" to your LD_LIBRARY_PATH in ~/.bashrc:
```bash
echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/usr/lib/nvidia-375"' >> ~/.bashrc
source ~/.bashrc
```

**Comment by pietern** [comment] 2017-05-04 17:47
@charlesrwest Can you try @kyu-sz suggestion and see if that works?

**Comment by charlesrwest** [comment] 2017-05-06 13:53
My apologies for the delayed response.  I am working full time on something unrelated and have a < 1 child.

As my GPU machine is used solely for deep learning, I ended up just wiping it and doing a fresh install without Caffe 1.  The fresh install appears to be working without issues.  I suspect the root problem was that I missed the environmental variables setting part of the CUDA install when I did it manually the first time (failing to update .bashrc)

**Comment by hma02** [comment] 2017-05-08 19:29
I have a similar issue on ubuntu 14. See below. 
I'm using gcc 4.8 and cudnn 5.1.5 (I tried gcc 5.4 and cudnn 5.1.10 as well. same problem)
It seems something related to cudnn. I wonder if anyone can help.

```bash
[ 87%] Building CXX object caffe2/CMakeFiles/Caffe2_GPU.dir/sgd/iter_op_gpu.cc.o
Linking CXX shared library libCaffe2_GPU.so
make[3]: Leaving directory `/export/mlrg/hma02/packages/caffe2/build'
[ 87%] Built target Caffe2_GPU
make[3]: Entering directory `/export/mlrg/hma02/packages/caffe2/build'
Scanning dependencies of target blob_gpu_test
make[3]: Leaving directory `/export/mlrg/hma02/packages/caffe2/build'
make[3]: Entering directory `/export/mlrg/hma02/packages/caffe2/build'
[ 87%] Building CXX object caffe2/CMakeFiles/blob_gpu_test.dir/core/blob_gpu_test.cc.o
Linking CXX executable binaries/blob_gpu_test
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionBackwardDataWorkspaceSize'
libCaffe2_GPU.so: undefined reference to `cudnnSetFilter4dDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnGetRNNLinLayerMatrixParams'
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionForwardAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionBackwardFilterWorkspaceSize'
libCaffe2_GPU.so: undefined reference to `cudnnCreateConvolutionDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyConvolutionDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSetTensorNdDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionForwardAlgorithmEx'
libCaffe2_GPU.so: undefined reference to `cudnnSetFilterNdDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSoftmaxBackward'
libCaffe2_GPU.so: undefined reference to `cudnnConvolutionForward'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionBackwardDataAlgorithmEx'
libCaffe2_GPU.so: undefined reference to `cudnnGetRNNLinLayerBiasParams'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionForwardAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnPoolingBackward'
libCaffe2_GPU.so: undefined reference to `cudnnCreateTensorDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyDropoutDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnRNNForwardInference'
libCaffe2_GPU.so: undefined reference to `cudnnConvolutionBackwardData'
libCaffe2_GPU.so: undefined reference to `cudnnCreateDropoutDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionBackwardDataAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnCreatePoolingDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyFilterDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnBatchNormalizationForwardInference'
libCaffe2_GPU.so: undefined reference to `cudnnActivationBackward'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyTensorDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnGetRNNParamsSize'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyRNNDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionForwardWorkspaceSize'
libCaffe2_GPU.so: undefined reference to `cudnnAddTensor'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyPoolingDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnGetFilterNdDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSoftmaxForward'
libCaffe2_GPU.so: undefined reference to `cudnnActivationForward'
libCaffe2_GPU.so: undefined reference to `cudnnGetRNNWorkspaceSize'
libCaffe2_GPU.so: undefined reference to `cudnnGetVersion'
libCaffe2_GPU.so: undefined reference to `cudnnPoolingForward'
libCaffe2_GPU.so: undefined reference to `cudnnDeriveBNTensorDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnRNNBackwardWeights'
libCaffe2_GPU.so: undefined reference to `cudnnSetTensor4dDescriptorEx'
libCaffe2_GPU.so: undefined reference to `cudnnGetRNNTrainingReserveSize'
libCaffe2_GPU.so: undefined reference to `cudnnCreateRNNDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnDropoutGetStatesSize'
libCaffe2_GPU.so: undefined reference to `cudnnSetPooling2dDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnConvolutionBackwardBias'
libCaffe2_GPU.so: undefined reference to `cudnnBatchNormalizationBackward'
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionBackwardFilterAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionBackwardFilterAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnCreateFilterDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSetActivationDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnTransformTensor'
libCaffe2_GPU.so: undefined reference to `cudnnConvolutionBackwardFilter'
libCaffe2_GPU.so: undefined reference to `cudnnSetStream'
libCaffe2_GPU.so: undefined reference to `cudnnFindConvolutionBackwardFilterAlgorithmEx'
libCaffe2_GPU.so: undefined reference to `cudnnRNNBackwardData'
libCaffe2_GPU.so: undefined reference to `cudnnCreateActivationDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSetTensor4dDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnDestroy'
libCaffe2_GPU.so: undefined reference to `cudnnDestroyActivationDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSetRNNDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnSetConvolution2dDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnBatchNormalizationForwardTraining'
libCaffe2_GPU.so: undefined reference to `cudnnGetConvolutionBackwardDataAlgorithm'
libCaffe2_GPU.so: undefined reference to `cudnnRNNForwardTraining'
libCaffe2_GPU.so: undefined reference to `cudnnSetDropoutDescriptor'
libCaffe2_GPU.so: undefined reference to `cudnnCreate'
collect2: error: ld returned 1 exit status
make[3]: *** [caffe2/binaries/blob_gpu_test] Error 1
make[3]: Leaving directory `/export/mlrg/hma02/packages/caffe2/build'
make[2]: *** [caffe2/CMakeFiles/blob_gpu_test.dir/all] Error 2
make[2]: Leaving directory `/export/mlrg/hma02/packages/caffe2/build'
make[1]: *** [all] Error 2   
make[1]: Leaving directory `/export/mlrg/hma02/packages/caffe2/build'
make: *** [all] Error 2
```

**Comment by pietern** [comment] 2017-05-09 17:45
@charlesrwest Thanks for confirming. I'll close this issue assuming this was an environment issue.

@hma02 Can you create a separate issue for this? I assume you have to set your LD_LIBRARY_PATH to where you have CuDNN installed.

**Closed as completed by pietern** 2017-05-09 17:45 UTC
Labels: build

**Comment by joshsuihn** [comment] 2017-05-11 07:12
Can you double-check or attach the logs when you run "cmake .." before "make"? Probably, you might miss some config like this: 

> -- CUDA detected: 8.0
> -- Added CUDA NVCC flags for: sm_60
> -- Found libcuda: /usr/lib/x86_64-linux-gnu/libcuda.so
> -- Found libnvrtc: /usr/local/cuda/lib64/libnvrtc.so

> -- Could NOT find CUDNN (missing:  CUDNN_LIBRARY)
> -- Could NOT find NCCL (missing:  NCCL_INCLUDE_DIR NCCL_LIBRARY)

**Comment by Scottyang8math** [comment] 2018-03-05 15:25
I have a same problem, but i solve it by making a link. 
Here is my log:
 `/usr/bin/ld: warning: libnvidia-fatbinaryloader.so.384.111, needed by /usr/lib/x86_64-linux-gnu/libcuda.so, not found (try using -rpath or -rpath-link)
/usr/lib/x86_64-linux-gnu/libcuda.so：undefined reference to ‘elf64_shnum’
......
`
I check the root `/usr/lib/x86_64-linux-gnu,` and there isn't a file name `libnvidia-fatbinaryloader.so.384.111` (in fact there is a file name `libnvidia-fatbinaryloader.so.384.86` , I don't know why). Then I search that file and find it in `/usr/lib/nvidia-384.`  Finally, I fix this problem by following code:

`sudo ln -s /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.111 /usr/lib/i386-linux-gnu/libnvidia-fatbinaryloader.so.384.111`.

**Comment by user-ZJ** [comment] 2018-09-06 02:14
@Scottyang8math I also have a same problem,but i solve ti by making a link with this command
> sudo ln -s /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.111 /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.384.111

i want to konw why you link to i386-linux-gnu
