### ISSUE TITLE
mpi_test.dir/mpi/mpi_test.cc.o:undefined refrence to symbol '_ZN3MPI8Datatype4FreeEv'

### ISSUE THREAD

**Issue by mingx9527** [facebookarchive/caffe2#2262] opened 2018-03-14 09:30 UTC
If this is a build issue, please fill out the template below.

### System information

* Operating system: Ubuntu16.04
* Compiler version: gcc-5.4
* CMake version: cmake-3.5.1
* CMake arguments:No args
* Relevant libraries/versions (e.g. CUDA): no GPU

### CMake summary output

```build files have been written to：/home/XXX/caffe2/build
******** Summary ********
<please paste summary output here>
```
![error](https://user-images.githubusercontent.com/36255328/37393882-5c4250de-27ad-11e8-94e2-c5c1e02ba0b5.png)

**Comment by pjh5** [comment] 2018-03-14 21:36
I notice that you're not using GPU. Do you still need MPI? If not, just pass -DUSE_MPI=OFF to your `cmake` command.

If you do want to use MPI, then can you tell me how you are trying to build Caffe2? Can you also give the full output of the `cmake` command that you runing during the build process? Also give the output of `mpirun --version`

**Comment by mingx9527** [comment] 2018-03-15 01:31
@pjh5 Thank you very much!  I modify the **option(USE_MPI "Use MPI" OFF)** in CMakeLists.txt; then build succeed, 
        but run " python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"   **return "Failure"**  ;  I am checking the problem.
       About full output of the cmake,  I can not ctrl+c the output because i build caffe2 in encryption server.  thank!

**Comment by pjh5** [comment] 2018-03-15 16:23
@mingx9527 run `from caffe2.python import core` in a python interpreter to get a better error message

**Comment by pjh5** [comment] 2018-03-19 23:02
Also a duplicate of #2144

**Closed as completed** 2018-03-28 17:09 UTC
Labels: build
